/*
 * Build content/starter.json and examples/plan.json from test/fixtures/plan.json.
 *
 * Run: node app/starter.build.mjs
 *
 * A fresh install has no training plan of its own. It still needs the parts of
 * the content file that are the APP rather than anyone's programme: the activity
 * catalog and lift catalog (both live on the `log-workout` and `planned` cards),
 * the rest-day card, the form shapes, gear kinds, journal behaviours, quick names,
 * the planner's kinds and the recommender's parameters. This script keeps those,
 * drops the climbing programme (sessions, tests, testing notes, the gym, the
 * evidence essays and the seeded achievements), keeps only the quota categories
 * that a starter card can fill, and strips the design-history quotes that name
 * the original user.
 *
 * The fixture is the full programme the test suites run against. The outputs
 * are committed. Re-run this after editing the shared parts of the fixture, and
 * `npm test` checks nothing has drifted.
 *
 * examples/plan.json is the starter plus a small, invented plan: two achievements,
 * four session cards over two sports, and one benchmark test. Every number and
 * name in it is made up. It is what Settings → "Use the example plan" imports.
 */

import { readFileSync, writeFileSync } from 'node:fs'

const SRC = new URL('../test/fixtures/plan.json', import.meta.url)
const OUT = new URL('../content/starter.json', import.meta.url)
const EXAMPLE_OUT = new URL('../examples/plan.json', import.meta.url)

/** The cards a blank install keeps: log anything, plan anything, rest. */
export const STARTER_CARDS = ['log-workout', 'planned', 'off']

/*
 * Drop `Name, date: "quote"` attributions, then any sentence still naming them.
 * These are developer notes about why a field exists; the reasoning survives
 * without the quote.
 */
function scrub(text) {
  if (typeof text !== 'string' || !/Ethan/.test(text)) return text
  const unquoted = text.replace(/Ethan[^.:]{0,40}:\s*(["'“‘])[\s\S]*?(["'”’])(?=\s|$)\s*/g, '')
  return unquoted
    .split(/(?<=[.!?])\s+/)
    .filter(s => !/Ethan/.test(s))
    .join(' ')
    .trim()
}

function deepScrub(value) {
  if (Array.isArray(value)) return value.map(deepScrub)
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, deepScrub(v)]))
  }
  return scrub(value)
}

export function buildStarter(plan) {
  const categories = (plan.quotaCategories || []).filter(c => c.discipline !== 'climbing')
  const catKeys = new Set(categories.map(c => c.key))

  const pk = plan.plannerKinds || {}
  const kinds = (pk.kinds || []).filter(k => !k.category || catKeys.has(k.category))
  const usedGroups = new Set(kinds.map(k => k.group))
  const plannerKinds = {
    ...pk,
    kinds,
    groups: (pk.groups || []).filter(g => usedGroups.has(g.key)),
  }

  const starter = {
    meta: {
      version: plan.meta?.version || '2.0',
      app: 'Bushido',
      note: 'Starter content for a new install: the activity and lift catalogs, the rest card, and the non-climbing quota categories. Add achievements in the app, or import a plan from Settings. Generated by app/starter.build.mjs.',
    },
    dailyMenu: (plan.dailyMenu || []).filter(m => STARTER_CARDS.includes(m.id)),
    recommender: plan.recommender,
    checkin: plan.checkin,
    outputsNote: plan.outputsNote,
    menuNote: plan.menuNote,
    achievements: [],
    quotaCategories: categories,
    formShapes: plan.formShapes,
    quickNames: plan.quickNames,
    gearKinds: plan.gearKinds,
    gearNote: plan.gearNote,
    journal: plan.journal,
    plannerKinds,
  }
  return deepScrub(starter)
}

/* ------------------------------------------------------- the example plan */

const done = [{ key: 'done', type: 'toggle', label: 'Completed' }]
const card = (o) => ({ level: 2, role: 'session', outputs: done, ...o })

/*
 * An invented six-week block for a beginner aiming at a 10K while building
 * general strength. Nothing here describes a real person.
 */
export const EXAMPLE = {
  achievements: [
    {
      id: 'example-10k', name: 'Run a 10K', short: '10K', icon: 'Footprints', date: null,
      blurb: 'An example goal. Six weeks of easy running with one longer run a week. Set a race date here and the weeks count down to it.',
      categories: ['run', 'bike'],
    },
    {
      id: 'example-strength', name: 'Strength base', short: 'Strength', icon: 'Dumbbell', date: null,
      blurb: 'An example goal. Two full-body sessions a week, plus a short mobility routine.',
      categories: ['lift', 'support'],
    },
  ],
  sessions: [
    card({
      id: 'example-easy-run', tier: 'easy · conversational', name: 'Easy run', minutes: 30, icon: 'Footprints',
      category: 'run',
      dose: 'Thirty minutes at a pace you could hold a conversation at.',
      whenInstead: 'The default run. Pick it on most running days.',
      protocol: {
        duration: '30 min',
        setup: ['Comfortable shoes. Any route.'],
        warmup: ['Five minutes of brisk walking.'],
        blocks: [{ name: 'Run', loadPct: null, steps: ['Run easy for 20 minutes.', 'Walk for 5 minutes to finish.'] }],
        cues: ['If you cannot talk in full sentences, slow down.'],
        stopIf: ['Sharp pain anywhere. Walk home.'],
        log: ['Done, yes/no'],
      },
    }),
    card({
      id: 'example-long-run', tier: 'once a week', name: 'Long run', minutes: 50, level: 3, icon: 'Route',
      category: 'run',
      dose: 'The longest run of the week, at easy pace. Add about five minutes a week.',
      whenInstead: 'Once a week, on a day with time to spare.',
      protocol: {
        duration: '40–60 min',
        setup: ['Water if it is warm.'],
        warmup: ['Five minutes of brisk walking.'],
        blocks: [{ name: 'Run', loadPct: null, steps: ['Run easy for the planned time.', 'Walk breaks are fine.'] }],
        cues: ['Easy the whole way. This is about time on your feet.'],
        stopIf: ['Sharp pain anywhere.'],
        log: ['Done, yes/no'],
      },
    }),
    card({
      id: 'example-full-body', tier: 'twice a week', name: 'Full-body strength', minutes: 45, icon: 'Dumbbell',
      category: 'lift',
      dose: 'Squat, push, pull and hinge, three sets each.',
      whenInstead: 'Twice a week, with a day between.',
      protocol: {
        duration: '45 min',
        setup: ['Dumbbells or a barbell.'],
        warmup: ['Five minutes on any machine, then one light set of each movement.'],
        blocks: [{
          name: 'Main', loadPct: null,
          steps: ['Goblet squat: 3 × 10.', 'Press-ups: 3 × 10.', 'One-arm row: 3 × 10 each side.', 'Romanian deadlift: 3 × 10.'],
        }],
        cues: ['Leave two reps in the tank on every set.'],
        stopIf: ['Joint pain, as opposed to muscle effort.'],
        log: ['Done, yes/no'],
      },
    }),
    card({
      id: 'example-mobility', tier: 'any day', name: 'Mobility', minutes: 15, level: 1, icon: 'Shield',
      category: 'support',
      dose: 'Fifteen minutes of easy hip, ankle and shoulder work.',
      whenInstead: 'On a rest day, or after a run.',
      protocol: {
        duration: '15 min',
        setup: ['Floor space.'],
        warmup: [],
        blocks: [{ name: 'Flow', loadPct: null, steps: ['Hip circles, 10 each way.', 'Calf raises, 2 × 15.', 'Arm circles, 30 s each way.'] }],
        cues: ['Nothing here should be hard.'],
        stopIf: ['Pain.'],
        log: ['Done, yes/no'],
      },
    }),
  ],
  tests: [
    {
      id: 'example-5k-trial', name: '5 km time trial',
      why: 'One number that says whether the running block is working. Repeat it every three weeks.',
      equipment: 'A measured 5 km route or a track, and a watch.',
      procedure: ['Warm up for ten minutes.', 'Run 5 km as evenly as you can.', 'Record the time.'],
      cautions: ['Do not run it the day after a long run.'],
      metrics: [{ key: 'minutes', label: 'Time', unit: 'min', hint: '30' }],
      interpretation: 'Compare only against your own earlier trials on the same route.',
    },
  ],
}

/** The starter plus the invented example: what "Use the example plan" imports. */
export function buildExample(starter) {
  return {
    ...starter,
    meta: {
      ...starter.meta,
      note: 'An invented example plan: a six-week block toward a first 10K plus a strength base, two sports, four session cards and one test. No real person, place or result. Generated by app/starter.build.mjs.',
    },
    achievements: EXAMPLE.achievements,
    tests: EXAMPLE.tests,
    dailyMenu: [...EXAMPLE.sessions, ...starter.dailyMenu],
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const plan = JSON.parse(readFileSync(SRC, 'utf8'))
  const starter = buildStarter(plan)
  writeFileSync(OUT, JSON.stringify(starter, null, 2) + '\n')
  console.log(`wrote content/starter.json: ${starter.dailyMenu.length} cards, ${starter.quotaCategories.length} categories, ${starter.plannerKinds.kinds.length} planner kinds`)
  const example = buildExample(starter)
  writeFileSync(EXAMPLE_OUT, JSON.stringify(example, null, 2) + '\n')
  console.log(`wrote examples/plan.json: ${example.dailyMenu.length} cards, ${example.achievements.length} achievements, ${example.tests.length} test`)
}
