// Writes src/lib/bodymapData.ts from react-body-highlighter's own polygon data,
// so the native body map draws the same bodies as the web without redrawing them.
//
//   mkdir /tmp/rbh && cd /tmp/rbh && npm pack react-body-highlighter@2.0.5 && tar -xzf *.tgz
//   node mobile/scripts/bodymap-data.mjs /tmp/rbh/package
//
// The package's entry renders a <div>, so it cannot be imported on React Native;
// its data module (src/assets/index.ts) is plain strings. This reads that file as
// text (no eval) and keeps only the muscle names and the polygon point lists.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkg = process.argv[2]
if (!pkg) {
  console.error('usage: node scripts/bodymap-data.mjs <unpacked react-body-highlighter package dir>')
  process.exit(1)
}

const meta = JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8'))
const license = readFileSync(join(pkg, 'LICENSE'), 'utf8').trim()
const metadata = readFileSync(join(pkg, 'src/component/metadata.ts'), 'utf8')
const assets = readFileSync(join(pkg, 'src/assets/index.ts'), 'utf8')

// MuscleType.CHEST -> 'chest'
const types = {}
const typeBlock = /export const MuscleType = \{([\s\S]*?)\}/.exec(metadata)?.[1] || ''
for (const m of typeBlock.matchAll(/(\w+):\s*'([^']+)'/g)) types[m[1]] = m[2]

function section(name) {
  const start = assets.indexOf(`export const ${name}`)
  if (start < 0) throw new Error(`no ${name} in assets`)
  const next = assets.indexOf('export const', start + 1)
  const body = assets.slice(start, next < 0 ? undefined : next)
  const out = []
  for (const m of body.matchAll(/muscle:\s*MuscleType\.(\w+),\s*svgPoints:\s*\[([\s\S]*?)\]/g)) {
    const muscle = types[m[1]]
    if (!muscle) throw new Error(`unknown MuscleType.${m[1]}`)
    const points = [...m[2].matchAll(/'([^']*)'/g)].map((p) => p[1].trim())
    if (!points.every((p) => /^[\d.\s-]+$/.test(p))) throw new Error(`odd points for ${muscle}`)
    out.push({ muscle, svgPoints: points })
  }
  if (!out.length) throw new Error(`${name} is empty`)
  return out
}

const anterior = section('anteriorData')
const posterior = section('posteriorData')

const fmt = (list) => list.map(({ muscle, svgPoints }) =>
  `  {\n    muscle: '${muscle}',\n    svgPoints: [\n${svgPoints.map((p) => `      '${p}',`).join('\n')}\n    ],\n  },`).join('\n')

const ts = `// GENERATED by scripts/bodymap-data.mjs from ${meta.name}@${meta.version} (src/assets/index.ts).
// Do not edit by hand; regenerate from the package instead. The polygons are the
// library's own drawing, in its 100x200 viewBox; nothing here was redrawn.
//
${license.split('\n').map((l) => `// ${l}`.trimEnd()).join('\n')}

export type BodySide = { muscle: string; svgPoints: string[] }[]

export const anteriorData: BodySide = [
${fmt(anterior)}
]

export const posteriorData: BodySide = [
${fmt(posterior)}
]
`

const here = dirname(fileURLToPath(import.meta.url))
const target = join(here, '..', 'src', 'lib', 'bodymapData.ts')
writeFileSync(target, ts)
console.log(`wrote ${target}: ${anterior.length} anterior, ${posterior.length} posterior regions`)
